import Link from "next/link";

export const metadata = {
  title: "Terms of Service · Mandate",
  description:
    "The terms under which Mandate is provided. Read before signing in.",
  alternates: { canonical: "/terms" },
};

export default function TermsPage() {
  return (
    <div className="mx-auto flex max-w-2xl flex-col gap-6 px-4 py-12 sm:px-6 sm:py-16">
      <Link
        href="/"
        className="inline-flex items-center gap-1 text-xs text-text-muted transition-colors hover:text-text"
      >
        <svg
          width="12"
          height="12"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
          aria-hidden="true"
        >
          <path d="m15 18-6-6 6-6" />
        </svg>
        Home
      </Link>
      <div>
        <div className="text-[11px] font-medium uppercase tracking-wider text-text-subtle">
          Legal
        </div>
        <h1 className="mt-1 text-3xl font-semibold tracking-tight text-text">
          Terms of Service
        </h1>
        <p className="mt-2 text-xs text-text-subtle">
          Last updated: May 2026
        </p>
      </div>

      <div className="prose prose-zinc dark:prose-invert max-w-none prose-headings:tracking-tight prose-headings:text-text prose-p:text-text-muted prose-li:text-text-muted prose-strong:text-text prose-a:text-accent">
        <h2>1. Acceptance</h2>
        <p>
          By signing in to Mandate (&ldquo;the Service&rdquo;), you agree
          to these terms. If you don&apos;t agree, don&apos;t use the Service.
        </p>

        <h2>2. What the Service is</h2>
        <p>
          Mandate is a research and decision-support tool that stress-tests
          investment theses against a configurable house view using
          multi-agent LLM analysis. It produces written analysis, not
          investment advice or recommendations to buy, sell, or hold any
          security.
        </p>

        <h2>3. No financial advice</h2>
        <p>
          Output from Mandate is generated by language models and external
          research APIs. It can contain factual errors, outdated information,
          or hallucinations. <strong>Do not rely on Mandate alone for
          investment decisions.</strong> Always verify against primary
          sources and exercise your own professional judgement.
        </p>

        <h2>4. Acceptable use</h2>
        <ul>
          <li>You will not attempt to bypass authentication or rate limits.</li>
          <li>
            You will not upload content that violates third-party rights
            or applicable law.
          </li>
          <li>
            You will not use Mandate to generate material misrepresentation
            in regulated filings, marketing material, or solicitations.
          </li>
        </ul>

        <h2>5. Your content</h2>
        <p>
          You retain ownership of memos, theses, and attachments you upload.
          You grant Mandate a non-exclusive license to process them for the
          sole purpose of providing the Service.
        </p>

        <h2>6. Availability</h2>
        <p>
          The Service is provided on an &ldquo;as-is, as-available&rdquo;
          basis without warranties of uptime, fitness for a particular
          purpose, or accuracy. We may take the Service down for maintenance
          or change features without notice.
        </p>

        <h2>7. Liability</h2>
        <p>
          To the maximum extent permitted by law, the operator&apos;s
          aggregate liability for any claim arising from your use of the
          Service is limited to the amount you paid to access the Service
          in the 12 months prior to the claim, or USD $50, whichever is
          greater.
        </p>

        <h2>8. Termination</h2>
        <p>
          You may stop using the Service and request account deletion at
          any time. The operator may suspend access for violations of
          these terms, security concerns, or non-payment (if applicable).
        </p>

        <h2>9. Governing law</h2>
        <p>
          These terms are governed by the laws of the jurisdiction in
          which the operator is established. Disputes will be resolved in
          that jurisdiction&apos;s courts.
        </p>

        <h2>10. Changes</h2>
        <p>
          We may update these terms. When we do, we&apos;ll update the
          &ldquo;last updated&rdquo; date above. Material changes will be
          notified to active accounts via email.
        </p>

        <h2>Contact</h2>
        <p>
          Questions about these terms: please reach out via the contact
          channel published with this deployment.
        </p>
      </div>
    </div>
  );
}
